name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.7.3"
          modules: qtdeclarative

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: QML Lint
        run: qmllint -I build -I build/RoStore build/RoStore/qml/Main.qml build/RoStore/qml/pages/HomePage.qml build/RoStore/qml/pages/AppDetailPage.qml build/RoStore/qml/components/AppCard.qml
